import type { BrandAction, BrandCompass, BrandContentSystem, BrandSpace, BrandThinkingItem, ContentConcept, PublishingCalendarItem } from "@/types";

const brandId = "mo-studio" as const;

const pillarIds = {
  culturalCaseStudies: "mo-pillar-cultural-case-studies",
  processIntelligence: "mo-pillar-process-intelligence",
  clientProof: "mo-pillar-client-proof",
  inHouseProof: "mo-pillar-in-house-proof",
  campaignLayer: "mo-pillar-campaign-layer",
  curatedPerspective: "mo-pillar-curated-perspective",
} as const;

const seriesIds = {
  caseStudyFrame: "mo-series-case-study-frame",
  studioThinking: "mo-series-studio-thinking",
  makingProcess: "mo-series-making-process",
  clientWork: "mo-series-client-work",
  originalBrands: "mo-series-original-brands",
  campaignLayer: "mo-series-campaign-layer",
  curatedPerspective: "mo-series-curated-perspective",
  midweek3: "mo-series-midweek-3",
} as const;

const conceptIds = {
  kakubin: "mo-concept-kakubin-contemporary-relevance",
  hibiki: "mo-concept-hibiki-experiential-design",
  authored: "mo-concept-authored-not-advertised",
  understood: "mo-concept-what-was-understood",
  aaiProof: "mo-concept-aai-brand-building-proof",
  masteryProof: "mo-concept-masteryatelier-craft-proof",
  referenceDirection: "mo-concept-reference-to-visual-direction",
  campaignMood: "mo-concept-shape-campaign-mood",
  magazineLogic: "mo-concept-japanese-magazine-logic",
  visualTrust: "mo-concept-visual-language-trust",
  questionTensionResponse: "mo-concept-question-tension-response",
  occasion: "mo-concept-product-into-occasion",
  midweek3: "mo-concept-midweek-3-music-notes",
} as const;

const brandCompass: BrandCompass = {
  strategy: {
    purpose: "Build meaningful visual worlds, products, campaigns, and brand expressions with depth, taste, cultural intelligence, and grounded execution.",
    coreBelief: "Good work is built from context. Visuals become stronger when they are shaped by culture, behavior, timing, and what the brand needs people to feel.",
    positioning: "MO Studio is the Massiveoutfit creative studio for brand worlds, campaign thinking, product direction, and visual systems.",
    promise: "Translate cultural context and studio taste into brand work that feels authored, useful, and alive.",
    tension: "Create work with cultural sharpness and visual discipline without becoming loud, salesy, or agency-generic.",
    neverBecome: "A portfolio dump, a surface-taste agency, or a studio that posts references without a point of view.",
  },
  visualLanguage: {
    photography: "Editorial but grounded: product, atmosphere, material, objects, client proof, in-house brands, and quiet process evidence.",
    composition: "Publication-inspired grids, structured case-study pages, controlled typography, and a rhythm between detail, context, and text.",
    colorMood: "Near-black command center restraint with purple, yellow, blue, lime, warm material tones, and clean editorial contrast.",
    texture: "Packaging, glass, print, leather, paper, fabric, food, music references, studio fragments, layout tests, and product details.",
    lighting: "Controlled soft light, warm experiential lighting when needed, and enough shadow to keep the work tactile.",
    references: ["Japanese design magazines", "Cultural case studies", "Product rituals", "Campaign mood boards", "Instrumental jazz atmosphere", "In-house brand worlds"],
    avoid: ["Loud agency hype", "Random reference dumping", "Generic portfolio captions", "Spotify screenshots", "Sales deck language"],
  },
  voice: {
    tone: "Calm, authored, intelligent, understated, specific, and culturally aware.",
    sentenceStyle: "Short to medium editorial sentences that explain what was understood before what was made.",
    wordsToUse: ["context", "tension", "response", "atmosphere", "ritual", "pacing", "visual language", "relevance"],
    wordsToAvoid: ["disruptive", "impactful", "game-changing", "vibes", "premium experience", "must-see"],
    captionLogic: "Name the cultural or behavioral context, explain the tension, then show how the studio would translate it into visual or experiential direction.",
    ctaStyle: "Quiet and direct. Let the point of view and proof create the invitation.",
    exampleLines: [
      "Every strong project begins with what was understood.",
      "References are not copied; they are translated into a point of view.",
      "A product becomes memorable when it belongs to a ritual, occasion, or feeling.",
    ],
  },
  brandWorld: {
    emotionalTone: "Calm authority, cultural sharpness, restraint, atmosphere, trust, and quiet confidence.",
    culturalTerritory: "Brand worlds, product culture, campaign thinking, Japanese editorial logic, drinks and dining rituals, music, objects, spaces, and contemporary lifestyle.",
    recurringThemes: ["Authored, not advertised", "What was understood", "Question / tension / response", "From reference to visual direction", "Original brands as proof", "Midweek 3"],
    coreTension: "The studio must prove capability and taste without becoming loud, salesy, or detached from real culture.",
    feeling: "A quiet studio table where references, products, music, campaign mood, and cultural context are shaped into useful direction.",
    whatMattersMost: "MO Studio should repeatedly show its way of thinking until the audience understands the studio's point of view.",
  },
};

const contentSystem: BrandContentSystem = {
  contentPillars: [
    {
      id: pillarIds.culturalCaseStudies,
      order: 1,
      name: "Cultural Case Studies",
      description: "Show how MO Studio thinks through brands, campaigns, products, cultural relevance, and contemporary reframing.",
      tags: ["Case studies", "Culture", "Campaign thinking"],
      color: "#8A63D2",
      active: true,
    },
    {
      id: pillarIds.processIntelligence,
      order: 2,
      name: "Process Intelligence",
      description: "Show how the studio works: references, mood, direction, structure, decision-making, and campaign atmosphere.",
      tags: ["Process", "Direction", "Studio thinking"],
      color: "#1D4DFF",
      active: true,
    },
    {
      id: pillarIds.clientProof,
      order: 3,
      name: "Client Proof",
      description: "Show selected client work and the value created through visual language, strategy, and cultural understanding.",
      tags: ["Client work", "Trust", "Proof"],
      color: "#F2C94C",
      active: true,
    },
    {
      id: pillarIds.inHouseProof,
      order: 4,
      name: "In-House Proof",
      description: "Use AAI, Masteryatelier, biro, and original brands as proof that MO Studio builds and operates its own brand worlds.",
      tags: ["AAI", "Masteryatelier", "Original brands"],
      color: "#B7FF00",
      active: true,
    },
    {
      id: pillarIds.campaignLayer,
      order: 5,
      name: "Campaign Layer",
      description: "Show how a product becomes an occasion, ritual, feeling, behavior, season, or experience.",
      tags: ["Campaign", "Occasion", "Ritual"],
      color: "#F38B2A",
      active: true,
    },
    {
      id: pillarIds.curatedPerspective,
      order: 6,
      name: "Curated Perspective",
      description: "Show cultural taste, music, Japanese magazine logic, objects, spaces, and observations that shape the studio's point of view.",
      tags: ["References", "Music", "Perspective"],
      color: "#8CE6FF",
      active: true,
    },
  ],
  contentSeries: [
    {
      id: seriesIds.caseStudyFrame,
      order: 1,
      name: "Case Study Frame",
      title: "Case Study Frame",
      description: "A repeatable structure for presenting work through cultural context, question, tension, and response.",
      pillarId: pillarIds.culturalCaseStudies,
      relatedPillarIds: [pillarIds.culturalCaseStudies],
      episodeStructure: "Context / question / tension / response / what was understood",
      productLogic: "Explain what was understood, not only what was made.",
      format: "Single Post, Carousel, Case Study",
      active: true,
    },
    {
      id: seriesIds.studioThinking,
      order: 2,
      name: "Studio Thinking",
      title: "Studio Thinking",
      description: "Short studio-thinking posts that explain how MO Studio frames work, understands clients, and makes decisions.",
      pillarId: pillarIds.processIntelligence,
      relatedPillarIds: [pillarIds.processIntelligence],
      episodeStructure: "Studio principle / short explanation / useful implication",
      productLogic: "Calm, clear, thoughtful, and free of agency-speak.",
      format: "Single Post, Studio Note",
      active: true,
    },
    {
      id: seriesIds.makingProcess,
      order: 3,
      name: "Making / Process",
      title: "Making / Process",
      description: "Show how references, mood, material, and direction become useful creative output.",
      pillarId: pillarIds.processIntelligence,
      relatedPillarIds: [pillarIds.processIntelligence],
      episodeStructure: "Reference / translation / decision / direction",
      productLogic: "Explain translation and decision-making rather than process for its own sake.",
      format: "Reel, Carousel, Process Post",
      active: true,
    },
    {
      id: seriesIds.clientWork,
      order: 4,
      name: "Client Work",
      title: "Client Work",
      description: "Show client-facing work in a way that communicates studio value, trust, and cultural intelligence.",
      pillarId: pillarIds.clientProof,
      relatedPillarIds: [pillarIds.clientProof],
      episodeStructure: "Client context / studio role / visual language / value created",
      productLogic: "Make the studio role clear without sounding like a sales deck.",
      format: "Single Post, Case Study, Carousel",
      active: true,
    },
    {
      id: seriesIds.originalBrands,
      order: 5,
      name: "Original Brands",
      title: "Original Brands",
      description: "Use MO Studio's own brands as proof of brand-building, product thinking, craft, and visual-world development.",
      pillarId: pillarIds.inHouseProof,
      relatedPillarIds: [pillarIds.inHouseProof],
      episodeStructure: "Original brand / proof point / studio method / what it shows",
      productLogic: "Explain what the original brand proves about the studio's approach.",
      format: "Single Post, Editorial Post, Product Detail",
      active: true,
    },
    {
      id: seriesIds.campaignLayer,
      order: 6,
      name: "Campaign Layer",
      title: "Campaign Layer",
      description: "Show how a product, object, or brand becomes an occasion, ritual, emotional moment, or experience.",
      pillarId: pillarIds.campaignLayer,
      relatedPillarIds: [pillarIds.campaignLayer],
      episodeStructure: "Product / audience behavior / occasion / feeling",
      productLogic: "Connect the product to timing, season, ritual, and emotion.",
      format: "Single Post, Case Study, Campaign Note",
      active: true,
    },
    {
      id: seriesIds.curatedPerspective,
      order: 7,
      name: "Curated Perspective",
      title: "Curated Perspective",
      description: "Share cultural observations that reveal studio taste and point of view.",
      pillarId: pillarIds.curatedPerspective,
      relatedPillarIds: [pillarIds.curatedPerspective],
      episodeStructure: "Reference / observation / studio implication",
      productLogic: "Specific, understated, culturally aware.",
      format: "Single Post, Editorial Post, Visual Reference",
      active: true,
    },
    {
      id: seriesIds.midweek3,
      order: 8,
      name: "Midweek 3",
      title: "Midweek 3",
      description: "A fortnightly music note featuring three sounds that reflect the studio's atmosphere, pace, and visual thinking.",
      pillarId: pillarIds.curatedPerspective,
      relatedPillarIds: [pillarIds.curatedPerspective],
      episodeStructure: "Three sounds / short notes / current studio rhythm",
      productLogic: "Connect sound to mood, space, memory, campaign rhythm, or cultural context.",
      format: "Single Post, Story Set",
      active: true,
    },
  ],
  pillarRotation: [
    { postNumber: 1, pillarId: pillarIds.processIntelligence, format: "Single Post", direction: "Studio Thinking or Curated Perspective on Monday." },
    { postNumber: 2, pillarId: pillarIds.culturalCaseStudies, format: "Single Post", direction: "Cultural Case Study on Wednesday unless Midweek 3 is scheduled." },
    { postNumber: 3, pillarId: pillarIds.culturalCaseStudies, format: "Carousel", direction: "Case study frame, Client Proof, or Campaign Layer on Thursday." },
    { postNumber: 4, pillarId: pillarIds.processIntelligence, format: "Reel", direction: "Process / Making or Original Brands on Friday." },
    { postNumber: 5, pillarId: pillarIds.curatedPerspective, format: "Single Post", direction: "Midweek 3 every fortnight on Wednesday." },
  ],
  contentRules: {
    productRole: "Product should be shown through cultural relevance, audience behavior, occasion, ritual, atmosphere, or proof of a larger brand system.",
    captionRules: "Explain what was understood before what was made. Keep the voice calm, specific, culturally aware, and never salesy.",
    visualRules: "Use editorial layouts, structured headings, controlled typography, restrained image use, quiet visual hierarchy, and publication-like pacing.",
    postingRules: "No Saturday or Sunday publishing. Mondays hold Studio Thinking or Curated Perspective. Wednesdays hold Cultural Case Studies except fortnightly Midweek 3. Thursdays hold case-study framing, Client Proof, or Campaign Layer. Fridays hold Process / Making or Original Brands.",
    avoid: "Avoid generic portfolio captions, shallow moodboard posts, loud advertising language, confidential client material, playlist screenshots, and references with no studio point of view.",
  },
};

const contentConcepts: ContentConcept[] = [
  {
    id: conceptIds.kakubin,
    brandId,
    title: "Cultural Case Study - Kakubin / Contemporary Relevance",
    seriesId: seriesIds.caseStudyFrame,
    pillarId: pillarIds.culturalCaseStudies,
    format: "Single Post",
    status: "Draft",
    scene: "A cultural case study on how Kakubin can be reintroduced with contemporary relevance without losing its familiar social rhythm. Focus on everyday drinking culture, food pairing, casual rituals, sharper visual language, and experiential design.",
    visualDirection: "Editorial layout inspired by Japanese design magazines. Use restrained typography, product imagery, cultural context, and structured case-study composition. Avoid looking like an advertisement.",
    captionDirection: "Explain how MO Studio thinks through cultural familiarity, not just campaign visuals. Relevance comes from understanding why a product already belongs in people's lives.",
    publishingTargetDate: "2026-05-06",
    notes: "This should position MO Studio as a studio that understands cultural context, not just visual styling.",
  },
  {
    id: conceptIds.hibiki,
    brandId,
    title: "Cultural Case Study - Hibiki / Experiential Design",
    seriesId: seriesIds.caseStudyFrame,
    pillarId: pillarIds.culturalCaseStudies,
    format: "Single Post",
    status: "Draft",
    scene: "A case study showing how Hibiki can be translated into experiential language through atmosphere, materiality, sound, lighting, and pacing. The brand experience should feel layered, composed, and impossible to rush.",
    visualDirection: "Refined editorial still life or event direction board with warm lighting, Japanese material references, music and atmosphere cues, and a premium but quiet layout.",
    captionDirection: "Frame the work as experiential design, not event decoration. Explain how atmosphere becomes part of brand memory.",
    publishingTargetDate: "2026-05-14",
    notes: "Connect Hibiki with contemporary instrumental jazz references and layered event atmosphere.",
  },
  {
    id: conceptIds.authored,
    brandId,
    title: "Studio Thinking - Authored, Not Advertised",
    seriesId: seriesIds.studioThinking,
    pillarId: pillarIds.processIntelligence,
    format: "Single Post",
    status: "Draft",
    scene: "A short studio-thinking post explaining that MO Studio's work should feel authored through context, restraint, and point of view instead of loud self-promotion.",
    visualDirection: "Minimal black background or editorial text-led graphic with strong title, short paragraph, restrained layout, and one quiet visual reference or studio image.",
    captionDirection: "Speak about the difference between showing work and selling work. Keep the tone calm, confident, and thoughtful.",
    publishingTargetDate: "2026-05-04",
    notes: "Strong positioning post for the studio.",
  },
  {
    id: conceptIds.understood,
    brandId,
    title: "Studio Thinking - What Was Understood",
    seriesId: seriesIds.studioThinking,
    pillarId: pillarIds.processIntelligence,
    format: "Single Post",
    status: "Draft",
    scene: "A studio note about how every strong client project begins with understanding: context, tension, protected truth, audience behavior, and the reason the work needs to exist.",
    visualDirection: "Text-led editorial post with a quiet supporting image. Use a case-study page style with headings: Context, Tension, Response.",
    captionDirection: "Good work is not only about what was made, but what was understood before anything was designed.",
    publishingTargetDate: "2026-05-11",
    notes: "This should become a recurring MO Studio logic.",
  },
  {
    id: conceptIds.aaiProof,
    brandId,
    title: "Original Brands - AAI as Brand-Building Proof",
    seriesId: seriesIds.originalBrands,
    pillarId: pillarIds.inHouseProof,
    format: "Single Post",
    status: "Idea",
    scene: "Use AAI as proof that MO Studio does not only advise brands, but builds and lives through its own brand world. Show identity, restraint, street culture, optimism, intent, product, visuals, and language.",
    visualDirection: "Editorial layout using AAI product imagery, captions, and brand-world references. It should feel like an internal case study, not a sales pitch.",
    captionDirection: "Position AAI as a living example of how a brand world is built through repetition, tone, and belief.",
    publishingTargetDate: "2026-05-15",
    notes: "Connect MO Studio's original brands to studio credibility.",
  },
  {
    id: conceptIds.masteryProof,
    brandId,
    title: "Original Brands - Masteryatelier as Craft Proof",
    seriesId: seriesIds.originalBrands,
    pillarId: pillarIds.inHouseProof,
    format: "Single Post",
    status: "Idea",
    scene: "Use Masteryatelier as proof of MO Studio's craft foundation. Focus on leather, handwork, material aging, custom footwear, and analog intervention on familiar forms.",
    visualDirection: "Close-up craft photography, leather texture, stitching, brass hardware, and worn-in details. Layout should feel tactile and precise.",
    captionDirection: "Explain how craft is not only an object, but a way of thinking through form, patience, and transformation.",
    publishingTargetDate: "2026-05-22",
    notes: "Strong bridge between product craft and studio thinking.",
  },
  {
    id: conceptIds.referenceDirection,
    brandId,
    title: "Process / Making - From Reference to Visual Direction",
    seriesId: seriesIds.makingProcess,
    pillarId: pillarIds.processIntelligence,
    format: "Reel",
    status: "Idea",
    scene: "Show how scattered references become a clear visual direction by moving from mood, material, cultural cues, and layout references into one coherent visual language.",
    visualDirection: "Reel or carousel showing reference images, notes, mood board fragments, layout tests, and final direction. Keep it editorial, not tutorial-like.",
    captionDirection: "References are not copied; they are translated into a point of view.",
    publishingTargetDate: "2026-05-01",
    notes: "Useful recurring process format.",
  },
  {
    id: conceptIds.campaignMood,
    brandId,
    title: "Process / Making - How We Shape a Campaign Mood",
    seriesId: seriesIds.makingProcess,
    pillarId: pillarIds.processIntelligence,
    format: "Reel",
    status: "Idea",
    scene: "A process post showing how MO Studio shapes mood for a campaign through tone, lighting, rhythm, material, setting, and emotional pacing.",
    visualDirection: "Use a sequence: raw reference, mood words, material direction, visual test, final campaign mood.",
    captionDirection: "Campaign mood is not decoration; it is the emotional structure that helps people remember the brand.",
    publishingTargetDate: "2026-05-08",
    notes: "Can be used for client or internal work.",
  },
  {
    id: conceptIds.magazineLogic,
    brandId,
    title: "Curated Perspective - Japanese Magazine Logic in Brand Work",
    seriesId: seriesIds.curatedPerspective,
    pillarId: pillarIds.curatedPerspective,
    format: "Single Post",
    status: "Idea",
    scene: "A perspective post on how Japanese magazines use pacing, restraint, layout, context, and atmosphere to make information feel desirable without shouting.",
    visualDirection: "Publication-inspired layout with editorial pacing, white space, image-text rhythm, and quiet visual hierarchy.",
    captionDirection: "Good brand work can learn from editorial logic: not everything needs to be a hook; some things need to be arranged with taste.",
    publishingTargetDate: "2026-05-18",
    notes: "Aligned with MO Studio's desired Instagram direction.",
  },
  {
    id: conceptIds.visualTrust,
    brandId,
    title: "Client Work - How Visual Language Creates Trust",
    seriesId: seriesIds.clientWork,
    pillarId: pillarIds.clientProof,
    format: "Single Post",
    status: "Idea",
    scene: "Explain how consistent visual language helps a brand feel trustworthy through typography, color, pacing, photography, material, copy tone, and spatial consistency.",
    visualDirection: "Case-study style composition with controlled examples or abstracted visual systems.",
    captionDirection: "Trust is built when the audience feels continuity across every touchpoint.",
    notes: "Can be used without revealing too much client detail.",
  },
  {
    id: conceptIds.questionTensionResponse,
    brandId,
    title: "Case Study Frame - Question / Tension / Response",
    seriesId: seriesIds.caseStudyFrame,
    pillarId: pillarIds.culturalCaseStudies,
    format: "Carousel",
    status: "Draft",
    scene: "A reusable case-study framework showing how MO Studio presents work through Question, Tension, and Response instead of only final visuals.",
    visualDirection: "Three-part editorial structure: Question, Tension, Response. Keep it clean and publication-like.",
    captionDirection: "Showing the thinking behind a project gives the work more weight and helps people understand the studio's role.",
    publishingTargetDate: "2026-05-07",
    notes: "Template for future client-work posts.",
  },
  {
    id: conceptIds.occasion,
    brandId,
    title: "Campaign Layer - Turning a Product into an Occasion",
    seriesId: seriesIds.campaignLayer,
    pillarId: pillarIds.campaignLayer,
    format: "Single Post",
    status: "Idea",
    scene: "A post about how campaign work turns a product into an occasion, habit, or emotional moment using drinks, gifting, dining, retail, or seasonal context.",
    visualDirection: "Editorial campaign board with product, setting, mood, gesture, and audience ritual.",
    captionDirection: "A product becomes more memorable when it is connected to a repeatable occasion or feeling.",
    publishingTargetDate: "2026-05-21",
    notes: "Useful for Suntory-related thinking and future pitches.",
  },
  {
    id: conceptIds.midweek3,
    brandId,
    title: "Curated Perspective - Midweek 3 / Music Notes",
    seriesId: seriesIds.midweek3,
    pillarId: pillarIds.curatedPerspective,
    format: "Single Post",
    status: "Idea",
    scene: "A fortnightly music note featuring three tracks or artists that reflect the studio's current atmosphere, pace, and visual thinking.",
    visualDirection: "Minimal editorial layout with three track names, short notes, and a quiet studio visual or abstract background. It should feel like a cultural magazine page, not a Spotify screenshot.",
    captionDirection: "Introduce the three selections as references shaping the studio's current rhythm. Keep the tone understated, specific, and culturally aware.",
    publishingTargetDate: "2026-05-13",
    notes: "Use every two weeks on Wednesday. It can connect to client work, campaign mood, seasonal atmosphere, or studio taste.",
  },
];

const publishingCalendar: PublishingCalendarItem[] = [
  {
    id: "mo-post-2026-05-01-reference-direction",
    brandId,
    date: "2026-05-01",
    title: "From Reference to Visual Direction",
    platform: "Instagram",
    type: "Post",
    pillarId: pillarIds.processIntelligence,
    seriesId: seriesIds.makingProcess,
    format: "Reel",
    status: "Idea",
    contentConceptId: conceptIds.referenceDirection,
    direction: "Show how mood, references, material cues, and layout inspiration become a clear visual direction.",
    sceneBrief: "Show how mood, references, material cues, and layout inspiration become a clear visual direction.",
    workingNotes: "Weekend after this can be used to collect references and prep next week's posts.",
  },
  {
    id: "mo-post-2026-05-04-authored",
    brandId,
    date: "2026-05-04",
    title: "Authored, Not Advertised",
    platform: "Instagram",
    type: "Post",
    pillarId: pillarIds.processIntelligence,
    seriesId: seriesIds.studioThinking,
    format: "Single Post",
    status: "Draft",
    contentConceptId: conceptIds.authored,
    direction: "A short positioning post on how MO Studio's work should feel authored through context and restraint, not loud self-promotion.",
    sceneBrief: "A short positioning post on how MO Studio's work should feel authored through context and restraint, not loud self-promotion.",
    workingNotes: "Strong studio positioning post.",
  },
  {
    id: "mo-post-2026-05-06-kakubin",
    brandId,
    date: "2026-05-06",
    title: "Kakubin / Contemporary Relevance",
    platform: "Instagram",
    type: "Post",
    pillarId: pillarIds.culturalCaseStudies,
    seriesId: seriesIds.caseStudyFrame,
    format: "Single Post",
    status: "Draft",
    contentConceptId: conceptIds.kakubin,
    direction: "Show how a familiar product can be reintroduced through contemporary social rhythm, food culture, and sharper visual framing.",
    sceneBrief: "Show how a familiar product can be reintroduced through contemporary social rhythm, food culture, and sharper visual framing.",
    workingNotes: "Keep it case-study oriented, not ad-like.",
  },
  {
    id: "mo-post-2026-05-07-question-tension-response",
    brandId,
    date: "2026-05-07",
    title: "Question / Tension / Response",
    platform: "Instagram",
    type: "Post",
    pillarId: pillarIds.culturalCaseStudies,
    seriesId: seriesIds.caseStudyFrame,
    format: "Carousel",
    status: "Draft",
    contentConceptId: conceptIds.questionTensionResponse,
    direction: "Introduce the studio's preferred case-study structure. Show how work is understood before it is designed.",
    sceneBrief: "Introduce the studio's preferred case-study structure. Show how work is understood before it is designed.",
    workingNotes: "This can become a repeatable format.",
  },
  {
    id: "mo-post-2026-05-08-campaign-mood",
    brandId,
    date: "2026-05-08",
    title: "How We Shape a Campaign Mood",
    platform: "Instagram",
    type: "Post",
    pillarId: pillarIds.processIntelligence,
    seriesId: seriesIds.makingProcess,
    format: "Reel",
    status: "Idea",
    contentConceptId: conceptIds.campaignMood,
    direction: "Show how lighting, material, rhythm, and emotional pacing create the feeling of a campaign.",
    sceneBrief: "Show how lighting, material, rhythm, and emotional pacing create the feeling of a campaign.",
    workingNotes: "Could be made with reference boards or behind-the-scenes assets.",
  },
  {
    id: "mo-post-2026-05-11-understood",
    brandId,
    date: "2026-05-11",
    title: "What Was Understood",
    platform: "Instagram",
    type: "Post",
    pillarId: pillarIds.processIntelligence,
    seriesId: seriesIds.studioThinking,
    format: "Single Post",
    status: "Draft",
    contentConceptId: conceptIds.understood,
    direction: "Explain that good work comes from understanding context, tension, audience, and truth before making visuals.",
    sceneBrief: "Explain that good work comes from understanding context, tension, audience, and truth before making visuals.",
    workingNotes: "Text-led editorial layout works well.",
  },
  {
    id: "mo-post-2026-05-13-midweek-3",
    brandId,
    date: "2026-05-13",
    title: "Midweek 3 - Music Notes",
    platform: "Instagram",
    type: "Post",
    pillarId: pillarIds.curatedPerspective,
    seriesId: seriesIds.midweek3,
    format: "Single Post",
    status: "Idea",
    contentConceptId: conceptIds.midweek3,
    direction: "A fortnightly music note featuring three sounds currently shaping the studio rhythm. Connect sound to atmosphere, pacing, campaign mood, and visual thinking.",
    sceneBrief: "A fortnightly music note featuring three sounds currently shaping the studio rhythm. Connect sound to atmosphere, pacing, campaign mood, and visual thinking.",
    workingNotes: "First Midweek 3 post. Suggested direction: Takuya Kuroda, Uyama Hiroto, Bohemian Voodoo.",
  },
  {
    id: "mo-post-2026-05-14-hibiki",
    brandId,
    date: "2026-05-14",
    title: "Hibiki / Experiential Design",
    platform: "Instagram",
    type: "Post",
    pillarId: pillarIds.culturalCaseStudies,
    seriesId: seriesIds.caseStudyFrame,
    format: "Single Post",
    status: "Draft",
    contentConceptId: conceptIds.hibiki,
    direction: "Show how Hibiki can be translated into atmosphere through sound, material, lighting, pacing, and experiential design.",
    sceneBrief: "Show how Hibiki can be translated into atmosphere through sound, material, lighting, pacing, and experiential design.",
    workingNotes: "Connect to music and atmosphere if useful.",
  },
  {
    id: "mo-post-2026-05-15-aai-proof",
    brandId,
    date: "2026-05-15",
    title: "AAI as Brand-Building Proof",
    platform: "Instagram",
    type: "Post",
    pillarId: pillarIds.inHouseProof,
    seriesId: seriesIds.originalBrands,
    format: "Single Post",
    status: "Idea",
    contentConceptId: conceptIds.aaiProof,
    direction: "Show AAI as a living example of internal brand worldbuilding through product, language, imagery, and belief.",
    sceneBrief: "Show AAI as a living example of internal brand worldbuilding through product, language, imagery, and belief.",
    workingNotes: "Use this to connect original brands to studio credibility.",
  },
  {
    id: "mo-post-2026-05-18-magazine-logic",
    brandId,
    date: "2026-05-18",
    title: "Japanese Magazine Logic in Brand Work",
    platform: "Instagram",
    type: "Post",
    pillarId: pillarIds.curatedPerspective,
    seriesId: seriesIds.curatedPerspective,
    format: "Single Post",
    status: "Idea",
    contentConceptId: conceptIds.magazineLogic,
    direction: "Explain how editorial pacing, context, restraint, and layout logic can make brand communication feel more intelligent.",
    sceneBrief: "Explain how editorial pacing, context, restraint, and layout logic can make brand communication feel more intelligent.",
    workingNotes: "Strong MO Studio perspective post.",
  },
  {
    id: "mo-post-2026-05-20-kakubin-carousel",
    brandId,
    date: "2026-05-20",
    title: "Kakubin / Contemporary Relevance",
    platform: "Instagram",
    type: "Post",
    pillarId: pillarIds.culturalCaseStudies,
    seriesId: seriesIds.caseStudyFrame,
    format: "Carousel",
    status: "Idea",
    contentConceptId: conceptIds.kakubin,
    direction: "A second version of the Kakubin case study, structured as a deeper multi-frame case study.",
    sceneBrief: "A second version of the Kakubin case study, structured as a deeper multi-frame case study.",
    workingNotes: "Can expand from the 6 May single post.",
  },
  {
    id: "mo-post-2026-05-21-occasion",
    brandId,
    date: "2026-05-21",
    title: "Turning a Product into an Occasion",
    platform: "Instagram",
    type: "Post",
    pillarId: pillarIds.campaignLayer,
    seriesId: seriesIds.campaignLayer,
    format: "Single Post",
    status: "Idea",
    contentConceptId: conceptIds.occasion,
    direction: "Show how campaign strategy connects a product to ritual, season, audience behavior, or emotional timing.",
    sceneBrief: "Show how campaign strategy connects a product to ritual, season, audience behavior, or emotional timing.",
    workingNotes: "Useful for drinks, gifting, dining, or retail campaigns.",
  },
  {
    id: "mo-post-2026-05-22-mastery-proof",
    brandId,
    date: "2026-05-22",
    title: "Masteryatelier as Craft Proof",
    platform: "Instagram",
    type: "Post",
    pillarId: pillarIds.inHouseProof,
    seriesId: seriesIds.originalBrands,
    format: "Single Post",
    status: "Idea",
    contentConceptId: conceptIds.masteryProof,
    direction: "Show Masteryatelier as proof of material intelligence, craft, aging, and analog intervention.",
    sceneBrief: "Show Masteryatelier as proof of material intelligence, craft, aging, and analog intervention.",
    workingNotes: "Use close-up details, leather, stitching, brass, and worn-in texture.",
  },
  {
    id: "mo-post-2026-05-25-authored-v2",
    brandId,
    date: "2026-05-25",
    title: "Authored, Not Advertised",
    platform: "Instagram",
    type: "Post",
    pillarId: pillarIds.processIntelligence,
    seriesId: seriesIds.studioThinking,
    format: "Reel or Single Post",
    status: "Idea",
    contentConceptId: conceptIds.authored,
    direction: "Revisit the idea in a more visual format, showing what authored work looks like compared to loud brand output.",
    sceneBrief: "Revisit the idea in a more visual format, showing what authored work looks like compared to loud brand output.",
    workingNotes: "Could become a reel with text overlays.",
  },
  {
    id: "mo-post-2026-05-27-midweek-3",
    brandId,
    date: "2026-05-27",
    title: "Midweek 3 - Music Notes",
    platform: "Instagram",
    type: "Post",
    pillarId: pillarIds.curatedPerspective,
    seriesId: seriesIds.midweek3,
    format: "Single Post",
    status: "Idea",
    contentConceptId: conceptIds.midweek3,
    direction: "Second fortnightly music note. Feature three sounds that reflect the studio's current mood, visual thinking, or campaign rhythm.",
    sceneBrief: "Second fortnightly music note. Feature three sounds that reflect the studio's current mood, visual thinking, or campaign rhythm.",
    workingNotes: "Keep it cultural and atmospheric, not like a playlist screenshot.",
  },
  {
    id: "mo-post-2026-05-28-hibiki-carousel",
    brandId,
    date: "2026-05-28",
    title: "Hibiki / Experiential Design",
    platform: "Instagram",
    type: "Post",
    pillarId: pillarIds.culturalCaseStudies,
    seriesId: seriesIds.caseStudyFrame,
    format: "Carousel",
    status: "Idea",
    contentConceptId: conceptIds.hibiki,
    direction: "A deeper case-study version showing experience layers: sound, material, light, pacing, memory.",
    sceneBrief: "A deeper case-study version showing experience layers: sound, material, light, pacing, memory.",
    workingNotes: "Good opportunity to show premium experiential thinking.",
  },
  {
    id: "mo-post-2026-05-29-reference-direction",
    brandId,
    date: "2026-05-29",
    title: "From Reference to Visual Direction",
    platform: "Instagram",
    type: "Post",
    pillarId: pillarIds.processIntelligence,
    seriesId: seriesIds.makingProcess,
    format: "Reel",
    status: "Idea",
    contentConceptId: conceptIds.referenceDirection,
    direction: "A second process post showing a different example of how references become visual direction.",
    sceneBrief: "A second process post showing a different example of how references become visual direction.",
    workingNotes: "Could be made from current MO Studio references or campaign mood boards.",
  },
];

const actions: BrandAction[] = [
  {
    id: "mo-action-prep-2026-05-02",
    brandId,
    title: "Prep MO Studio posts for 4-8 May",
    status: "Next",
    priority: "Medium",
    linkedItemType: "Brand",
    linkedItemId: brandId,
    dueDate: "2026-05-02",
    nextMove: "Prepare Authored, Not Advertised; Kakubin / Contemporary Relevance; Question / Tension / Response; and How We Shape a Campaign Mood.",
    notes: "Prepare Authored, Not Advertised; Kakubin / Contemporary Relevance; Question / Tension / Response; and How We Shape a Campaign Mood.",
  },
  {
    id: "mo-action-prep-2026-05-09",
    brandId,
    title: "Prep MO Studio posts for 11-15 May",
    status: "Next",
    priority: "Medium",
    linkedItemType: "Brand",
    linkedItemId: brandId,
    dueDate: "2026-05-09",
    nextMove: "Prepare What Was Understood; Midweek 3; Hibiki / Experiential Design; and AAI as Brand-Building Proof.",
    notes: "Prepare What Was Understood; Midweek 3; Hibiki / Experiential Design; and AAI as Brand-Building Proof.",
  },
  {
    id: "mo-action-prep-2026-05-16",
    brandId,
    title: "Prep MO Studio posts for 18-22 May",
    status: "Next",
    priority: "Medium",
    linkedItemType: "Brand",
    linkedItemId: brandId,
    dueDate: "2026-05-16",
    nextMove: "Prepare Japanese Magazine Logic in Brand Work; Kakubin carousel; Turning a Product into an Occasion; and Masteryatelier as Craft Proof.",
    notes: "Prepare Japanese Magazine Logic in Brand Work; Kakubin carousel; Turning a Product into an Occasion; and Masteryatelier as Craft Proof.",
  },
  {
    id: "mo-action-prep-2026-05-23",
    brandId,
    title: "Prep MO Studio posts for 25-29 May",
    status: "Next",
    priority: "Medium",
    linkedItemType: "Brand",
    linkedItemId: brandId,
    dueDate: "2026-05-23",
    nextMove: "Prepare Authored, Not Advertised version two; Midweek 3; Hibiki carousel; and From Reference to Visual Direction.",
    notes: "Prepare Authored, Not Advertised version two; Midweek 3; Hibiki carousel; and From Reference to Visual Direction.",
  },
  {
    id: "mo-action-review-2026-05-30",
    brandId,
    title: "Review May MO Studio content and plan June rotation",
    status: "Next",
    priority: "Medium",
    linkedItemType: "Brand",
    linkedItemId: brandId,
    dueDate: "2026-05-30",
    nextMove: "Review what was posted, what performed clearly, what needs more proof, and plan the next June pillar rotation.",
    notes: "Review what was posted, what performed clearly, what needs more proof, and plan the next June pillar rotation.",
  },
];

const thinking: BrandThinkingItem[] = [
  {
    id: "mo-thinking-weekly-content-rhythm",
    brandId,
    title: "MO Studio Weekly Content Rhythm",
    type: "Workflow",
    status: "Useful",
    possibleUse: "Publishing calendar rhythm",
    body: "Monday is for Studio Thinking or Curated Perspective. Wednesday is for Cultural Case Studies, except every fortnight when it becomes Midweek 3. Thursday is for case-study framing, client proof, or campaign-layer thinking. Friday is for process, making, or original-brand proof. Weekends are not for publishing; they are for preparation, generation, and review.",
  },
  {
    id: "mo-thinking-concept-to-publishing-flow",
    brandId,
    title: "MO Studio Concept to Publishing Flow",
    type: "Workflow",
    status: "Useful",
    possibleUse: "Concept workflow",
    body: "Every post should move through this flow: Content Concept -> Visual Direction -> Caption Direction -> Asset Preparation -> Publishing Calendar -> Scheduled -> Published. Concepts should stay light at first. Full captions should be written later, only after the concept and visual direction are clear.",
  },
  {
    id: "mo-thinking-content-status-logic",
    brandId,
    title: "MO Studio Content Status Logic",
    type: "Workflow",
    status: "Useful",
    possibleUse: "Status hygiene",
    body: "Use simple statuses so the publishing system remains practical. Concept statuses: Idea, Draft, Ready, Scheduled, Published, Archived. Publishing statuses: Idea, Draft, Asset Ready, Caption Ready, Scheduled, Published. Do not overwork a concept too early.",
  },
  {
    id: "mo-thinking-repetition-rule",
    brandId,
    title: "MO Studio Repetition Rule",
    type: "Strategy",
    status: "Useful",
    possibleUse: "Content strategy",
    body: "Repeat strong ideas instead of constantly creating new ones. MO Studio should repeatedly show Authored, Not Advertised; What Was Understood; Question / Tension / Response; From Reference to Visual Direction; Cultural Case Study; Original Brands as Proof; and Midweek 3. Repetition helps the audience understand the studio's point of view.",
  },
];

export const moStudioBrandSpaceDefaults = {
  overview: {
    description: "Creative studio shaping brand worlds, products, campaigns, and visual systems.",
    summary: "MO Studio builds culturally grounded brand worlds, campaign layers, original brands, and visual systems through strategy, taste, and execution.",
    focus: "Cultural case studies / Process intelligence / Client proof / In-house proof / Campaign layer / Curated perspective",
    cadence: "Monday thinking, Wednesday case study or Midweek 3, Thursday case-study/client/campaign proof, Friday process or original-brand proof",
    nextAction: "Operate the May MO Studio content rhythm: concepts, publishing calendar, weekend prep actions, and workflow thinking.",
    horizon: "May content rotation: May 1-30",
  } satisfies Partial<Pick<BrandSpace, "description" | "summary" | "focus" | "cadence" | "nextAction" | "horizon">>,
  brandCompass,
  contentSystem,
  contentConcepts,
  publishingCalendar,
  actions,
  thinking,
};
